# prometheus_data/prometheus.yml

# config file for prometheus

# global config
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ai-monitoring-stack'
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: ['alertmanager:9093']
rule_files:
  - "alert_rules.yml"
scrape_configs:
- job_name: prometheus
  static_configs:
    - targets: ['prometheus:9090']
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
- job_name: 'fastapi'
  scrape_interval: 10s
  metrics_path: /metrics
  static_configs:
    - targets: ['web:8000']
- job_name: 'cadvisor'
  scrape_interval: 15s
  static_configs:
    - targets: ['cadvisor:8080']
- job_name: 'node-exporter'
  scrape_interval: 15s
  static_configs:
    - targets: ['node-exporter:9100']